version: '3.8'

services:
  servidorA:
    build:
      context: ./servers/servidorA
      container_name: servidorA
      dockerfile: Dockerfile
    environment:
      - SERVER_ID=servidorA
      - PORT=5000
      - OUTROS_SERVIDORES=servidorB:5002,servidorC:5003
    ports:
      - "5000:5000":
      # - "5001:5001"
    networks:
      - rede_passcom

  servidorB:
    build:
      context: ./servers/servidorB
      container_name: servidorB
      dockerfile: Dockerfile
    environment:
      - SERVER_ID=servidorB
      - PORT=5002
      - OUTROS_SERVIDORES=servidorA:5000,servidorC:5003
    ports:
      - "5002:5002"
    networks:
      - rede_passcom
      
  servidorC:
    build:
      context: ./servers/servidorC
      container_name: servidorC
      dockerfile: Dockerfile
    environment:
      - SERVER_ID=servidorC
      - PORT=5003
      - OUTROS_SERVIDORES=servidorA:5000,servidorB:5002
    ports:
      - "5003:5003"
    networks:
      - rede_passcom
      
  
  cliente:
    build:
      context: ./cliente
      dockerfile: Dockerfile
    environment:
      - REACT_APP_API_URL=http://servidorA:5000  # URL para acessar o servidor principal
    ports:
      - "3000:3000"  # Porta exposta para acessar o front-end do cliente
    depends_on:
      - servidorA
      - servidorB
      - servidorC
    networks:
      - rede_passcom
    stdin_open: true  # para manter o terminal interativo aberto
    tty: true         # permite a interação com o usuário


networks:
  rede_passcom:
    driver: bridge
